import { Inter } from "next/font/google";
import "./globals.css";
import { StickyNavbar } from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div>
          <StickyNavbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
